version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: orderservice_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fast_api
    ports:
      - "6005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fast_api"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
 